name: Go

on:
  push:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.6
        
    - name: Test
      run: env GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go test -v ./...

    - name: Build voiui win/amd64
      run: env GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -o voiui.exe cmd/voiui/main.go

    - name: Prepare version file
      run: echo $GITHUB_SHA > version

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: dev
        artifacts: "voiui.exe"
        prerelease: true